version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: gestor-mysql
    restart: unless-stopped
    ports:
      - "${MYSQL_PORT:-3307}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-gestor_root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-gestor}
      MYSQL_USER: ${MYSQL_USER:-gestor_app}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-gestor_app}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2
    container_name: gestor-phpmyadmin
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - "${PHPMYADMIN_PORT:-8081}:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: ${MYSQL_USER:-gestor_app}
      PMA_PASSWORD: ${MYSQL_PASSWORD:-gestor_app}
      UPLOAD_LIMIT: 256M

volumes:
  mysql_data:
    driver: local
